### ISSUE TITLE
Error after success purchase

### ISSUE THREAD

**Issue by stoianov46** [vendelieu/telegram-bot#191]
Version: 6.2.0
After call `answerPreCheckoutQuery` i receive error. As temp solution i use deleteWebhook(dropPendingUpdates = true).
Maybe problem with 'test' purchases.
After this error - bot stop working even after reload.

```
Exception in thread "DefaultDispatcher-worker-4" kotlinx.serialization.MissingFieldException: Field 'orderInfo' is required for type with serial name 'eu.vendeli.tgbot.types.payment.SuccessfulPayment', but it was missing at path: $.result[0].message.successfulPayment
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:95)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:78)
	at eu.vendeli.tgbot.types.Message$$serializer.deserialize(Message.kt:129)
	at eu.vendeli.tgbot.types.Message$$serializer.deserialize(Message.kt:129)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:78)
	at eu.vendeli.tgbot.types.Update$$serializer.deserialize(Update.kt:46)
	at eu.vendeli.tgbot.types.Update$$serializer.deserialize(Update.kt:46)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:538)
	at kotlinx.serialization.internal.CollectionLikeSerializer.readElement(CollectionSerializers.kt:80)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168)
	at eu.vendeli.tgbot.types.internal.Response$Success$$serializer.deserialize(Response.kt:16)
	at eu.vendeli.tgbot.types.internal.Response$Success$$serializer.deserialize(Response.kt:16)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:165)
	at eu.vendeli.tgbot.utils.BotRequestExtensionsKt$makeRequestAsync$2$1.invokeSuspend(BotRequestExtensions.kt:96)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [CoroutineName(TgBot), StandaloneCoroutine{Cancelling}@35feebd2, Dispatchers.Default]
Caused by: kotlinx.serialization.MissingFieldException: Field 'orderInfo' is required for type with serial name 'eu.vendeli.tgbot.types.payment.SuccessfulPayment', but it was missing
	at kotlinx.serialization.internal.PluginExceptionsKt.throwMissingFieldException(PluginExceptions.kt:20)
	at eu.vendeli.tgbot.types.payment.SuccessfulPayment.<init>(SuccessfulPayment.kt:18)
	at eu.vendeli.tgbot.types.payment.SuccessfulPayment$$serializer.deserialize(SuccessfulPayment.kt:18)
	at eu.vendeli.tgbot.types.payment.SuccessfulPayment$$serializer.deserialize(SuccessfulPayment.kt:18)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69)
	... 33 more
```

**Comment by vendelieu** [comment]
A bugfix has been released in version 6.4.1.
If problem still exist please reopen issue :)

**Comment by stoianov46** [comment]
Hi) Thnx you! 
Bug fixd.

Can i ask about better way to handle successful payment?
Now i do in next way and it work
`
    @UpdateHandler([UpdateType.MESSAGE])
    suspend fun onSuccessPayment(user: User, update: ProcessedUpdate, bot: TelegramBot) {
        println("SuccessfulPayment: ${update.origin.message?.successfulPayment}")
    }
```

But how i can handle success payment message with special update type, something like this (got compilation error):
    @UpdateHandler([UpdateType.MESSAGE])
    suspend fun onSuccessPaymentX(user: User, update: SuccessfulPayment, bot: TelegramBot) {
        //...
    }

**Comment by vendelieu** [comment]
Yeah, basically there's only several options you have :)

But you can make little improvement of your first example: 
```
    @UpdateHandler([UpdateType.MESSAGE])
    suspend fun onSuccessPayment(user: User, update: MessageUpdate, bot: TelegramBot) {
        println("SuccessfulPayment: ${update.message.successfulPayment}")
    }
```

or you can create some kind of resolver like described [here](https://github.com/vendelieu/telegram-bot/wiki/Activity-invocation) where you take SuccessfulPayment from update and use second example that you described :)
