### ISSUE TITLE
Kotlin 2.1.0: Problem with `suspend fun <T : Any?> access$toResult$tBotRequestExtensionsKt

### ISSUE THREAD

**Issue by devjn** [vendelieu/telegram-bot#295]
**Describe the bug**
```
file:///home/runner/work/telegram-bot/telegram-bot/telegram-bot/src/commonMain/kotlin/eu/vendeli/tgbot/utils/BotRequestExtensions.kt:1:1 org.jetbrains.kotlin.backend.common.CompilationException: Back-end: Please report this problem https://kotl.in/issue
/home/runner/work/telegram-bot/telegram-bot/telegram-bot/src/commonMain/kotlin/eu/vendeli/tgbot/utils/BotRequestExtensions.kt:1:1
Problem with `suspend fun <T : Any?> access$toResult$tBotRequestExtensionsKt($receiver: HttpResponse, type: KSerializer<T>, bot: TelegramBot): Response<out T> $receiver.toResult<T>(type = type, bot = bot)
`
Details: Internal error in body lowering: java.lang.ClassCastException: class org.jetbrains.kotlin.ir.expressions.impl.IrExpressionBodyImpl cannot be cast to class org.jetbrains.kotlin.ir.expressions.IrBlockBody (org.jetbrains.kotlin.ir.expressions.impl.IrExpressionBodyImpl and org.jetbrains.kotlin.ir.expressions.IrBlockBody are in unnamed module of loader 'app')
	at org.jetbrains.kotlin.ir.backend.js.lower.coroutines.AbstractSuspendFunctionsLoweringKt.getSuspendFunctionKind(AbstractSuspendFunctionsLowering.kt:536)
	at org.jetbrains.kotlin.ir.backend.js.lower.coroutines.AbstractSuspendFunctionsLoweringKt.getSuspendFunctionKind$default(AbstractSuspendFunctionsLowering.kt:507)
	at org.jetbrains.kotlin.ir.backend.js.lower.coroutines.AbstractSuspendFunctionsLowering.transformSuspendFunction(AbstractSuspendFunctionsLowering.kt:80)
	at org.jetbrains.kotlin.ir.backend.js.lower.coroutines.AbstractSuspendFunctionsLowering.lower(AbstractSuspendFunctionsLowering.kt:70)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitBody$lambda$2(Lower.kt:187)
	at org.jetbrains.kotlin.ir.backend.js.WholeWorldStageController.restrictTo(WholeWorldStageController.kt:29)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitBody(Lower.kt:186)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitBody(Lower.kt:165)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitExpressionBody(IrElementVisitor.kt:93)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitExpressionBody(Lower.kt:165)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitExpressionBody(Lower.kt:165)
	at org.jetbrains.kotlin.ir.expressions.IrExpressionBody.accept(IrExpressionBody.kt:21)
	at org.jetbrains.kotlin.ir.declarations.IrFunction.acceptChildren(IrFunction.kt:57)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitDeclaration(Lower.kt:174)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitDeclaration(Lower.kt:165)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitFunction(IrElementVisitor.kt:42)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitFunction(Lower.kt:165)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitFunction(Lower.kt:165)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitSimpleFunction(IrElementVisitor.kt:69)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitSimpleFunction(Lower.kt:165)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitSimpleFunction(Lower.kt:165)
	at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:39)
	at org.jetbrains.kotlin.backend.common.LowerKt.runOnFilePostfix(Lower.kt:144)
	at org.jetbrains.kotlin.backend.common.LowerKt.runOnFilePostfix$default(Lower.kt:137)
	at org.jetbrains.kotlin.backend.common.BodyLoweringPass.lower(Lower.kt:76)
	at org.jetbrains.kotlin.backend.common.FileLoweringPass.lower(Lower.kt:42)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt.makeIrModulePhase$lambda$5(PhaseBuilders.kt:110)
	at org.jetbrains.kotlin.backend.common.phaser.PhaseBuildersKt$createSimpleNamedCompilerPhase$1.phaseBody(PhaseBuilders.kt:69)
	at org.jetbrains.kotlin.backend.common.phaser.SimpleNamedCompilerPhase.phaseBody(CompilerPhase.kt:226)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedCompilerPhase.invoke(CompilerPhase.kt:113)
	at org.jetbrains.kotlin.ir.backend.js.CompilerWithICKt.lowerPreservingTags(compilerWithIC.kt:114)
	at org.jetbrains.kotlin.ir.backend.js.JsCompilerKt.compileIr(jsCompiler.kt:141)
	at org.jetbrains.kotlin.ir.backend.js.JsCompilerKt.compile(jsCompiler.kt:55)
	at org.jetbrains.kotlin.ir.backend.js.JsCompilerKt.compile$default(jsCompiler.kt:38)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler$Ir2JsTransformer.lowerIr(K2JSCompiler.kt:124)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler$Ir2JsTransformer.makeJsCodeGenerator(K2JSCompiler.kt:147)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler$Ir2JsTransformer.compileAndTransformIrNew(K2JSCompiler.kt:157)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.kt:526)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.kt:105)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:102)
	at org.jetbrains.kotlin.cli.common.CLICompiler.exec(CLICompiler.kt:316)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1554)
	at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ClassCastException: class org.jetbrains.kotlin.ir.expressions.impl.IrExpressionBodyImpl cannot be cast to class org.jetbrains.kotlin.ir.expressions.IrBlockBody (org.jetbrains.kotlin.ir.expressions.impl.IrExpressionBodyImpl and org.jetbrains.kotlin.ir.expressions.IrBlockBody are in unnamed module of loader 'app')
	... 58 more
```

**To Reproduce**
1. Update to Kotlin 2.1.0
2. Build project

**Comment by vendelieu** [comment]
Thank you for report,
can you try with 7.6.0 version

**Comment by devjn** [comment]
Yeap, it works now, thanks for quick fix 👍
